sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: The Great Project
description: Helping families
url: http://www.greatleicester.org.uk
baseurl: 
email: info@greatleicester.org.uk
github: aylestoneallotments/www.aylestoneallotments.co.uk
logo_path: /logo.png

#  Social media settings

facebook: "voluntaryactionleics"
twitter : "valonline"
instagram: ""

permalink: pretty

analyticstracking: " "

paginate: 5
paginate_path: "/news/:num/"

#  Timezone
timezone: Europe/London

#  Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','_config.yml']
  media: img
  metadata:
    _posts:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"