sass:
  style: compressed

encoding: utf-8

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: The Great Project
description: Helping families move toward employment and training in Leicester and Leicestershire
url: https://www.greatproject.org.uk
baseurl: 
email: info@greatproject.org.uk
github: 
copyright: 'The GREAT Project is funded by Big Lottery Fund and the European Social Fund. The service is delivered by Voluntary Action LeicesterShire (VAL).</p><p>
<a href="http://www.valonline.org.uk/">Voluntary Action LeicesterShire</a> is the trading name of Voluntary Action Leicester registered charity (No. 509300) Registered in England and Wales. ©2016'

#  Social media settings

facebook: "thegreatprojectleicester"
twitter: "TheGREATProj"
permalink: pretty

# Services

analyticstracking: "UA-88639134-1"

# Pagination

paginate: 5
paginate_path: "/news/:num/"

#  Timezone
timezone: Europe/London

exclude:
  - bower.json
  - grunt

# Conditional Stylesheets

conditionalstylesheets:
  - target: "ie9"
    path: "/css/ie9.css"

#  Configuration for prose.io online editor
prose:
  ignore: 
    - '_includes'
    - 'assets'
    - '_assets'
    - '_layouts'
    - '_plugins'
    - '/.jekyll-metadata'
    - 'feed.xml'
    - 'js'
    - 'css'
    - '_sass'
    - 'CNAME'
    - '.bowerrc'
    - '.gitignore'
    - '404.md'
    - 'news.xml'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'license.md'
    - 'README.md'
    - '_config.yml'
    - 'bower.json'
    - 'favicon.ico'
  media: img
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "summary"
        field:
          label: "Summary"
          element: "textarea"
          value: null
      - name: "thumbnail-image"
        field:
          label: "Thumbnail Image"
          element: "text"
          placeholder: "/img/placeholder-thumbnail.png"
          value: "/img/placeholder.jpg"
      - name: "layout"
        field:
          label: "Layout"
          element: "select"
          value: "default"
          options:
            - name: 'Post'
              value: 'post'
            - name: 'Default'
              value: 'default'
            - name: 'No Sidebars'
              value: 'no-sidebars'
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"