--- 
analyticstracking: UA-88639134-1
baseurl: ~
collections: 
  events: 
    output: true
    permalink: "/events/:path/"
  partnernews: 
    output: true
    permalink: "/partnernews/:path/"
conditionalstylesheets: 
  - 
    path: /css/ie9.css
    target: ie9
copyright: "The GREAT Project  is funded by the European Social Fund and the National Lottery, through the Big Lottery Fund. The service is delivered by Voluntary Action LeicesterShire (VAL).</p><p> <a href=\"http://www.valonline.org.uk/\">Voluntary Action LeicesterShire</a> is the trading name of Voluntary Action Leicester registered charity (No. 509300) Registered in England and Wales. ©"
description: "Helping families move toward employment and training in Leicester and Leicestershire"
email: info@greatproject.org.uk
encoding: utf-8
exclude: 
  - bower.json
  - grunt
facebook: thegreatprojectleicester
gems: 
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
github: ~
markdown: kramdown
paginate: 6
paginate_path: "/news/:num/"
permalink: pretty
prose: 
  ignore: 
    - _includes
    - assets
    - _assets
    - _layouts
    - _plugins
    - /.jekyll-metadata
    - feed.xml
    - js
    - css
    - _sass
    - CNAME
    - .bowerrc
    - .gitignore
    - 404.md
    - news.xml
    - Gemfile
    - Gemfile.lock
    - license.md
    - README.md
    - _config.yml
    - bower.json
    - favicon.ico
  media: img
  metadata: 
    _events: 
      - 
        field: 
          element: text
          label: Title
        name: title
      - 
        field: 
          element: textarea
          label: Summary
          value: ~
        name: summary
      - 
        field: 
          element: text
          label: When
          value: ""
        name: when
      - 
        field: 
          element: text
          label: Where
          value: ""
        name: venue
      - 
        field: 
          element: hidden
          label: Layout
          value: event
        name: layout
      - 
        field: 
          element: checkbox
          label: Published
          value: "true"
        name: published
    _partnernews: 
      - 
        field: 
          element: text
          label: title
        name: title
      - 
        field: 
          element: text
          label: Date
          value: CURRENT_DATETIME
        name: date
      - 
        field: 
          element: textarea
          label: Summary
          value: ~
        name: summary
      - 
        field: 
          element: text
          label: "Thumbnail Image"
          placeholder: /img/placeholder-thumbnail.png
          value: /img/placeholder.jpg
        name: thumbnail-image
      - 
        field: 
          element: select
          label: Layout
          options: 
            - 
              name: Post
              value: post
            - 
              name: Default
              value: default
            - 
              name: "No Sidebars"
              value: no-sidebars
          value: default
        name: layout
      - 
        field: 
          element: checkbox
          label: Published
          value: "true"
        name: published
    _posts: 
      - 
        field: 
          element: text
          label: title
        name: title
      - 
        field: 
          element: text
          label: Date
          value: CURRENT_DATETIME
        name: date
      - 
        field: 
          element: textarea
          label: Summary
          value: ~
        name: summary
      - 
        field: 
          element: text
          label: "Thumbnail Image"
          placeholder: /img/placeholder-thumbnail.png
          value: /img/placeholder.jpg
        name: thumbnail-image
      - 
        field: 
          element: select
          label: Layout
          options: 
            - 
              name: Post
              value: post
            - 
              name: Default
              value: default
            - 
              name: "No Sidebars"
              value: no-sidebars
          value: default
        name: layout
      - 
        field: 
          element: checkbox
          label: Published
          value: "true"
        name: published
    _posts/static: 
      - 
        field: 
          element: text
          label: title
        name: title
      - 
        field: 
          element: textarea
          label: Summary
          value: ~
        name: summary
      - 
        field: 
          element: hidden
          value: page
        name: layout
      - 
        field: 
          element: text
          label: Permalink
          value: ""
        name: permalink
sass: 
  style: compressed
timezone: Europe/London
title: "The Great Project"
twitter: TheGREATProj
url: "https://www.greatproject.org.uk"
