sass:
    style: compressed
encoding: utf-8
markdown: kramdown
gems:
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-feed
title: 'The Great Project'
description: 'Helping families move toward employment and training in Leicester and Leicestershire'
url: 'https://www.greatproject.org.uk'
baseurl: null
email: info@greatproject.org.uk
github: null
copyright: 'The GREAT Project is funded by the European Social Fund and The National Lottery Community Fund. It is delivered by <a href="http://www.valonline.org.uk">Voluntary Action LeicesterShire</a> (VAL). VAL is the trading name of Voluntary Action Leicester. Registered charity no. 509300. Registered in England & Wales. ©'
facebook: yesprojectleics
facebook: thegreatprojectleicester
twitter: TheGREATProj
permalink: pretty
analyticstracking: UA-88639134-1
paginate: 6
paginate_path: '/news/:num/'
timezone: Europe/London
exclude:
    - bower.json
    - grunt
conditionalstylesheets:
    -
        target: ie9
        path: /css/ie9.css
collections:
    events:
        output: true
        permalink: '/events/:path/'
    partnernews:
        output: true
        permalink: '/partnernews/:path/'
    pages:
        output: true
        permalink: '/staticpages/:path/'
prose:
    media: img
    ignore:
        - _includes
        - assets
        - _assets
        - _layouts
        - _plugins
        - /.jekyll-metadata
        - feed.xml
        - js
        - css
        - _sass
        - CNAME
        - .bowerrc
        - .gitignore
        - 404.md
        - news.xml
        - Gemfile
        - Gemfile.lock
        - license.md
        - README.md
        - _config.yml
        - bower.json
        - favicon.ico
    metadata:
        _posts:
            - {name: title, field: {element: text, label: title}}
            - {name: date, field: {label: Date, element: text, value: CURRENT_DATETIME}}
            - {name: summary, field: {label: Summary, element: textarea, value: null}}
            - {name: thumbnail-image, field: {label: 'Thumbnail Image', element: text, placeholder: /img/placeholder-thumbnail.png, value: /img/placeholder.jpg}}
            - {name: layout, field: {label: Layout, element: select, value: default, options: [{name: Post, value: post}, {name: Default, value: default}, {name: 'No Sidebars', value: no-sidebars}]}}
            - {name: published, field: {label: Published, element: checkbox, value: 'true'}}
        _events:
            - {name: title, field: {element: text, label: Title}}
            - {name: summary, field: {label: Summary, element: textarea, value: null}}
            - {name: when, field: {label: When, element: text, value: ""}}
            - {name: venue, field: {label: Where, element: text, value: ""}}
            - {name: layout, field: {label: Layout, element: hidden, value: event}}
            - {name: published, field: {label: Published, element: checkbox, value: 'true'}}
        _partnernews:
            - {name: title, field: {element: text, label: title}}
            - {name: date, field: {label: Date, element: text, value: CURRENT_DATETIME}}
            - {name: summary, field: {label: Summary, element: textarea, value: null}}
            - {name: thumbnail-image, field: {label: 'Thumbnail Image', element: text, placeholder: /img/placeholder-thumbnail.png, value: /img/placeholder.jpg}}
            - {name: layout, field: {label: Layout, element: select, value: default, options: [{name: Post, value: post}, {name: Default, value: default}, {name: 'No Sidebars', value: no-sidebars}]}}
            - {name: published, field: {label: Published, element: checkbox, value: 'true'}}
        _pages:
            - {name: title, field: {element: text, label: title}}
            - {name: summary, field: {label: Summary, element: textarea, value: null}}
            - {name: layout, field: {element: hidden, value: default}}
            - {name: permalink, field: {element: text, label: Permalink, value: ""}}
            - {name: layout, field: {label: Layout, element: select, value: default, options: [{name: Post, value: post}, {name: Default, value: default}, {name: 'No Sidebars', value: no-sidebars}]}}
            - {name: published, field: {label: Published, element: checkbox, value: 'true'}}