  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "personal website of person"
  #   bio: "a paragraph of text explaining the persons background"

  - name: "Heather Roythone-Finch"
    img: "/img/profiles/heather-roythorne-finch.jpg"
    bio: "Test"
  - name: "Nesta Birrell"
    img: "/img/profiles/nesta-birrell.jpg"
    bio: "Nesta Birrell is Project Administrator for the GREAT Project, supporting the team, acting as first contact for Navigators and Delivery Partners, and taking referrals for the project. A former housing officer for the City Council, Nesta has recently completed a degree in International Relations with the Open University and is interested in strengthening community and local resilience. She believes strongly in the maxim ‘think global, act local’."
