  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "personal website of person"
  #   bio: "a paragraph of text explaining the persons background"

  - name: "Krishna Patel"
    role: "GREAT Team Leader"
    phone: "0116 2575035"
    img: "/img/profiles/Krishna-Patel.jpg"
  - name: "Chantal Brotherhood"
    role: "GREAT Team Leader"
    phone: "0116 2575035"
    img: "/img/profiles/Chantal-Brotherhood.jpg"
  - name: "Harinder Kang"
    role: "Employment Support Officer"
    phone: "07776 154002"
    img: "/img/profiles/Harinder-Kang.jpg"
  - name: "Emma Whitmore"
    role: "Employment Support Officer"
    phone: "07816 218949"
    img: "/img/profiles/Emma-Whitmore.jpg"
  - name: "Suzi Hailes"
    role: "Employment Support Officer"
    phone: "07741 736248"
    img: "/img/profiles/Suzi-Hailes.jpg"
  - name: "Anita Gardiner"
    role: "Employment Support Officer"
    phone: "07741 736522"
    img: "/img/profiles/Anita-Gardiner.jpg"
  - name: "Eileen Cusey"
    role: "Employment Support Officer"
    phone: "07880 241048"
    img: "/img/profiles/Eileen-Cusey.jpg"
  - name: "Yachna Gadhia"
    role: "Employment Coordinator"
    phone: "07741 660765"
    img: "/img/profiles/Yachna-Gadhia.jpg"
  - name: "Leah Fazakerley"
    role: "Employment Support Officer"
    phone: "07741 844734"
    img: '/img/profiles/Leah-Fazakerley.jpg'
  - name: "Diana Georgescu"
    role: "Employment Support Officer"
    phone: "07891 500034"
    img: "/img/profiles/Diana-Georgescu.jpg"
  - name: "Desrie Hadley"
    role: "Employment Support Officer"
    phone: "07741 741627"
    img: "/img/profiles/Desrie-Hadley.jpg"
  - name: "Aarti Thobhani"
    role: "Employment Coordinator"
    phone: "0116 2575035"
    img: "/img/profiles/Aarti-Thobhani.jpg"
  - name: "Kenton Hall"
    role: "Employment Coordinator"
    phone: "0116 2575035"
    img: "/img/profiles/Kenton-Hall.jpg"