  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "presonal website of person"
  - name: "Wendy Bricket"
    img: "/img/profiles/profile-placeholder.gif"
    role: "Chair"
    email: "wendy.b@valonline.org.uk"
  - name: "Heather Roythorne Finch"
    img: "/img/profiles/profile-placeholder.gif"
    role: "Secretary"
    phone: "Profile phone"
    email: "heather.rf@valonline.org.uk"