  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "personal website of person"
  #   bio: "a paragraph of text explaining the persons background"
  - name: "Heather Roythone-Finch"
    img: "/img/partners/bitc.png"
    bio: "Business in the Community is a charity which works to ensure that age, gender, race and health do not limit an employee’s engagement and success in the workplace. They’ll offer a range of work readiness activities to Great Project participants as well as work experiences placements."
    url: "http://www.bitc.org.uk"